### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by amirhosseindavoody** [polynote/polynote#671] opened 2019-11-18 22:31 UTC
Is there any plans to make polynote available in windows?

**Comment by jeremyrsmith** [comment] 2019-11-20 17:56
Welcome! Thanks for the question!

Several folks have reported being able to use polynote with WSL. As far as official support for the Windows platform (sans WSL), we don't have any plans mainly because we don't have any users on Windows, so it would be quite hard for us to test it. We mainly deploy Polynote on Linux-based servers, rather than running it locally (which is only really done for development).

Have you tried it with WSL?

**Comment by tdudzik** [comment] 2019-11-21 16:19
It doesn't work on my machine with WSL 2.0. I can run it and access it with curl from WSL but when I try to connect with Polynote from Chrome on Windows I receive an error `This site can't be reached`.

I don't know how WSL works in detail but it's quite weird. Jupyter Notebook or just random server with node and express works without any problems.

**Comment by ctivanovich** [comment] 2019-11-22 02:22
Same, and this issue is a duplicate: #555

**Comment by jonathanindig** [comment] 2020-01-27 21:46
Duplicate of #555

**Closed** 2020-01-27 21:46 UTC
