### ISSUE TITLE
Renaming notebook prefixed by a directory doesn't work properly

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#653] opened 2019-11-12 00:27 UTC
Something strange going on with directories and renaming. 

Renaming `/foo/bar` to `/foo/baz` ends up with just `/baz`.
Renaming `/foo/bar` to `/foo/foo/baz` ends up with `/foo/baz`. 
Renaming `/foo/bar` to `/blah/foo/baz` ends up with `/blah/foo/baz`. 
Renaming `/bar` to `/foo/baz` ends up with `/foo/baz`.

**Comment by jeremyrsmith** [comment] 2019-11-12 15:23
I don't see the same issues, but I do see an issue when renaming to a second folder level. Somehow it throws a `NoSuchFileException`. Not sure why this doesn't happen for the first level of folders, but I'll take a look.

**Comment by jeremyrsmith** [comment] 2019-11-12 16:38
The `NoSuchFileException` should be fixed by #656, but I won't close this issue because I couldn't reproduce what you were talking about. I didn't test across mounts, so maybe it has to do with renaming across mounts rather than folders per se?

**Comment by jeremyrsmith** [comment] 2019-11-12 17:15
For posterity, I was able to repro the above behavior when renaming the notebook into the same folder (when it's in a folder). Fixed the bug in #656

**Closed** 2019-11-12 18:16 UTC
Labels: bug
