### ISSUE TITLE
Vanilla polynote build fails with NPE on start.

### ISSUE THREAD

**Issue by kamilkloch** [polynote/polynote#685] opened 2019-11-27 10:59 UTC
Checked both for Scala 2.11 and 2.12.

EDIT: Steps to reproduce:
 1. git clone polynote
 2. sbt dist
 3.  run target/scala-2.12/polynote/polynote

Tarball from the polynote releases page works fine.
```
╠─An unchecked error was produced.
║ java.lang.NullPointerException
║ 	at java.io.Reader.<init>(Reader.java:78)
║ 	at java.io.InputStreamReader.<init>(InputStreamReader.java:129)
║ 	at scala.io.BufferedSource.reader(BufferedSource.scala:24)
║ 	at scala.io.BufferedSource.bufferedReader(BufferedSource.scala:25)
║ 	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader$lzycompute(BufferedSource.scala:35)
║ 	at scala.io.BufferedSource.scala$io$BufferedSource$$charReader(BufferedSource.scala:33)
║ 	at scala.io.BufferedSource.scala$io$BufferedSource$$decachedReader(BufferedSource.scala:62)
║ 	at scala.io.BufferedSource.mkString(BufferedSource.scala:91)
║ 	at polynote.server.Server$$anonfun$4$$anonfun$apply$4.apply(Server.scala:45)
║ 	at polynote.server.Server$$anonfun$4$$anonfun$apply$4.apply(Server.scala:47)
║ 	at zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:133)
║ 	at zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:127)
║ 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:333)
║ 	at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:602)
║ 	at zio.internal.FiberContext$$anonfun$7.run(FiberContext.scala:602)
║ 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
║ 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
║ 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by JD557** [comment] 2019-11-27 14:45
Seems like the UI might not have been compiled.

Can you try running `npm install` and `npm run dist` from the `polynote-frontend` folder first, and only then running `sbt dist`?

**Comment by kamilkloch** [comment] 2019-11-27 15:34
it helped, thanks! Should I add this info somewhere into the polynote doc files?

**Comment by JD557** [comment] 2019-11-27 20:36
It would probably make more sense to fix the build.sbt to build the frontend when `sbt dist` is called

There's already a `buildUI` and a `distUI` task (https://github.com/polynote/polynote/blob/master/build.sbt#L65-L71), so I guess that's the expected behavior.

**Comment by jeremyrsmith** [comment] 2019-11-28 00:00
Yeah, it would be great to have `dist` depend on `distUI`, but the problem is that `distUI` takes a reaaaaly long time and I frequently use `dist` to test things on a cloud box. Maybe we need some smart things in the build to make `buildUI` or `distUI` happen only if the UI hasn't been built or is out-of-date. PRs for that would be super welcome, otherwise we should document that you can't really build `dist` without building the frontend first. Apologies for the confusion @kamilkloch! I'll close this and we'll open a new issue for either fixing the build or documenting the build needs.

**Closed by jeremyrsmith** 2019-11-28 00:00 UTC
