### ISSUE TITLE
我就问一句,我就看个结果怎么这么累,网上查了半天都不知道怎么能看到我想要的结果.文档也不够全.

### ISSUE THREAD

**Issue by yangyongyongyong** [polynote/polynote#1224] opened 2021-12-05 09:14 UTC
![image](https://user-images.githubusercontent.com/46118358/144740630-22182943-6b4a-46e7-8272-282e17c45e3a.png)
我想要的:
![image](https://user-images.githubusercontent.com/46118358/144740658-1fcdf771-1793-425d-9486-3789d2257bc6.png)

**Comment by jonathanindig** [comment] 2021-12-10 17:12
Hi @yangyongyongyong, I'm sorry but I can't read your issue as it's in a language I do not speak. 

I'm going to close this issue, but feel free to open a new issue, in English, and we'd be more than happy to help!

**Closed by jonathanindig** 2021-12-10 17:12 UTC

**Comment by jeremyrsmith** [comment] 2021-12-10 20:16
From the included screenshots, I'm guessing the issue is that `show tables` gets you a `DataFrame` result and you have to visualize it in order to see anything. Which is annoying.

Not sure we can really differentiate between "I wanted this to be materialized now" vs "This is just an intermediate DF and it will take 46 hours to materialize so please don't". Maybe the SQL interpreter by default should just show the table as a result (I think maybe it used to do that)

**Comment by yangyongyongyong** [comment] 2021-12-10 20:41
Why not spark-Shell or Jupyter, Zeppelin if it's so hard to display dataframe

**Comment by yangyongyongyong** [comment] 2021-12-10 20:43
Does it make sense to you that a notebook can't easily display a dataframe? The damn drawing parameter is always clicked incorrectly.Why not display the results directly like Sparkshell.I love Scala, but Polynote is so anti-human.

**Comment by jeremyrsmith** [comment] 2021-12-10 21:24
@yangyongyongyong FWIW, I agree with you that the SQL interpreter should probably just materialize/show the results by default rather than just giving you an output DF that you have to visualize.

I think that from the SQL interpreter, there's never that much of a question about whether you want to execute that DataFrame or not. Most people aren't making SQL cells in order to get DataFrames that they go on to do other stuff with.

That being said, your comment came off as a little bit combative. Just letting you know, in case it wasn't what you intended.

**Comment by jeremyrsmith** [comment] 2021-12-10 21:37
Also,
> Why not spark-Shell or Jupyter, Zeppelin if it's so hard to display dataframe
