### ISSUE TITLE
Having the notebook open concurrently seems to prevent dependency loading from working

### ISSUE THREAD

**Issue by jonathanindig** [polynote/polynote#111] opened 2019-03-05 19:35 UTC
@faisalzs was loading new dependencies on his notebook. I connected to it and the dependency download seemed to hang. When I refreshed my page, the download on @faisalzs page started moving again. Every time I refreshed the download moved forward until eventually succeeding.

**Comment by jeremyrsmith** [comment] 2019-03-14 18:52
Something with crossing the streams...

**Comment by jeremyrsmith** [comment] 2019-03-21 19:57
I couldn't reproduce this by just using multiple tabs... maybe it's something two people need to cooperate in reproducing?

**Comment by jeremyrsmith** [comment] 2019-03-21 20:37
Couldn't reproduce; it might only happen in coursier fetcher. Moving this to next milesone.

**Comment by indig** [comment] 2019-03-26 19:58
We were able to repro with coursier fetcher.

**Comment by jeremyrsmith** [comment] 2019-08-02 20:20
Seems to be fixed

**Closed by jeremyrsmith** 2019-08-02 20:20 UTC
Labels: bug
