### ISSUE TITLE
Spark missing from 0.3.12-2.11-spark2.4 image

### ISSUE THREAD

**Issue by q-ams** [polynote/polynote#1133] opened 2021-04-07 03:44 UTC
**Description**
Spark is not installed in the `polynote/polynote:0.3.12-2.11-spark2.4` image.

**Reproduction**
1. `printenv` shows `SPARK_HOME` is set to `/opt/spark` which doesn't exist
2. ` ls -R / | grep "spark"` matches only "polynote-spark-runtime.jar"
3. Trying to run the Scala Spark to Pandas notebook fails because spark-submit cannot be found.

**Environment**
Using the polynote/polynote:0.3.12-2.11-spark2.4 image modified with:
```
USER root
ENTRYPOINT ["/bin/bash"]
```
and tagged "polynote-testing". Starting the image with `docker run -it --rm -p 8192:8192 -p 4040:4040 polynote-testing`

**Screenshots**
<img width="1484" alt="Screen Shot 2021-04-07 at 1 39 50 pm" src="https://user-images.githubusercontent.com/82018769/113807156-f5416100-97a6-11eb-9c5d-6b0fe4c8bdf5.png">

**Comment by jonathanindig** [comment] 2021-04-07 04:31
Hi @q-ams, unfortunately this is a known issue with that version (see #1001). The latest image (`0.4.0`) should work. 

Closing as a duplicate of #1001 Feel free to create a new issue if you run into any problems running `0.4.0`. Thanks!

**Closed by jonathanindig** 2021-04-07 04:31 UTC
