### ISSUE TITLE
Kernel doesn't star

### ISSUE THREAD

**Issue by iogiul** [polynote/polynote#545] opened 2019-10-25 12:20 UTC
Hi, 
very interesting project. I am trying to use the notebook, but everytime I try to use a code cell (both with python and scala)  I obtain  the message error 
_"scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found."_ followed by _"Uncaught exception: object java.lang.Object in compiler mirror not found. (scala.reflect.internal.MissingRequirementError)"_ and the kernel doesn't start

**Comment by Hoffmannxd** [comment] 2019-10-25 14:16
Which is your JDK version? I think you probably are using JDK 11 (default) instead of JDK 8, that is the correct version. I got the same error.

**Comment by Hoffmannxd** [comment] 2019-10-25 14:42
Can I add this check as a PR in the server module?

**Comment by jonathanindig** [comment] 2019-10-25 16:49
Hi @iogiul and thanks for the issue report! I believe that @Hoffmannxd is correct in saying that this looks like a duplicate of #530 and should be solved by using JDK 8. 

Thanks @Hoffmannxd for your help here! A PR would be most welcome, thank you!

**Closed by jonathanindig** 2019-10-25 16:49 UTC

**Comment by jeremyrsmith** [comment] 2019-10-25 17:15
@Hoffmannxd I think this problem is fixed by #547 (updating to Scala 2.11.12, which has better support for JDK 9+). But it might not hurt to emit a warning for JDK > 8 for people using Spark, as it goes against Spark's requirements as well.
