### ISSUE TITLE
Allow to propagate JAVA_OPTS to the Polynote in docker for the Scala LocalKernel

### ISSUE THREAD

**Issue by REASY** [polynote/polynote#718] opened 2020-01-02 18:08 UTC
Would be great to be able to pass JVM args, like `UseCGroupMemoryLimitForHeap` to the Polynote  Scala LocalKernel, when run in Docker.

**Comment by jeremyrsmith** [comment] 2020-01-06 17:11
Duplicate of #695

**Closed by jeremyrsmith** 2020-01-06 17:11 UTC
